import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import Banner from '../components/banner'
import ABoutMe from '../components/aboutme'
import SovtechSection from '../components/sovtechSection'
import Me from '../components/meSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>SovTech Mini-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

         <Navbar />

      <div className='flex justify-between'>

          {/* Left */}
          <div className="bg-gray-900 w-8/12 h-screen p-0 m-0"> 
            <Banner />
            <ABoutMe />
            <SovtechSection />
          </div>

          {/* Right */}
          <div className="bg-white w-4/12 h-screen p-0 m-0">
            <Me />
          </div>
      </div>
    </div>
  )
}

