import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import Banner from '../components/banner'
import ABoutMe from '../components/aboutme'
import SovtechSection from '../components/sovtechSection'
import Me from '../components/meSection'

export default function Home() {
  return (
    <div className='flex justify-between'>
      <Head>
        <title>SovTech Mini-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Left */}
      <div class="bg-gray-900 w-8/12 h-screen p-0 m-0"> 
      <Navbar />
      <Banner />
      <ABoutMe />
      <br></br>
      <SovtechSection />
      </div>

      {/* Right */}
      <div class="bg-white w-4/12 h-screen p-0 m-0">
        <Me />
      </div>
    </div>
  )
}

